language: rust
cache: cargo
rust: stable
env:
  global:
    - TARGET=x86_64-unknown-linux-gnu
matrix:
  include:
    - rust: beta
    - rust: nightly
    - env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: osx
      env: TARGET=i686-apple-darwin
    - os: osx
      rust: beta
      env: TARGET=x86_64-apple-darwin
    - os: osx
      rust: beta
      env: TARGET=i686-apple-darwin
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
before_install:
  - rustup target add $TARGET || true
  - travis_wait cargo install rustfmt --force || true
before_script:
  - export PATH="$PATH":~/.cargo/bin
  - echo "\$ rustfmt --version"
  - cd emerald-core
  - cargo fmt -- --version
  - cd ..
script:
  - export RUST_BACKTRACE=1
  - cd emerald-core
  - cargo fmt -- --verbose --write-mode=diff
  - cd ../emerald-cli
  - cargo fmt -- --verbose --write-mode=diff
  - cargo test --all --target=$TARGET --verbose
  - cargo build --all --target=$TARGET --verbose --release
#  - cargo doc --no-deps
