language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
notifications:
  email:
    on_success: never
before_install:
  - rustup target add $TARGET || true
  - travis_wait cargo install rustfmt --force || true
before_script:
  - export PATH="$PATH":~/.cargo/bin
  - echo "\$ rustfmt --version"
  - cd emerald-core
  - cargo fmt -- --version
  - cd ..
script:
  - export RUST_BACKTRACE=1
  - cd emerald-core
  - cargo fmt -- --verbose --write-mode=diff
  - cargo test --all --target=$TARGET --verbose
  - cargo build --all --target=$TARGET --verbose --release
