language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
before_script:
  - |
    (travis_wait cargo install rustfmt || true) &&
    cargo fmt -- --version
script:
  - |
    export RUST_BACKTRACE=1 &&
    cargo fmt -- --verbose --write-mode=diff &&
    (test "$TRAVIS_RUST_VERSION" == nightly || cargo build --verbose) &&
    (test "$TRAVIS_RUST_VERSION" != nightly || cargo build --verbose --features "dev") &&
    cargo test --verbose &&
    cargo doc --no-deps
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
