[package]
name = "emerald-rs"
version = "0.0.1"
authors = ["Dmitry Ulanov <dulanov@gmail.com>"]
description = "Ethereum classic bootstrap library written in Rust"
homepage = "http://etcdevteam.com"
repository = "https://github.com/ethereumproject/emerald-rs"
documentation = "https://docs.rs/emerald-rs"
keywords = ["rust", "bootstrap", "ethereum-classsic", "blockchain", "crypto-wallet"]
categories = ["ethereum-classic"]
readme = "README.adoc"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "ethereumproject/emerald-rs" }
appveyor = { repository = "ethereumproject/emerald-rs" }

[dependencies]
log = "0.3"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
# optional dependencies
reqwest = { version = "0.4", optional = true }
clippy = {version = "*", optional = true}

[dev-dependencies]
env_logger = "0.4"

[features]
default = ["http"]
http = ["reqwest"]
